// <auto-generated />
namespace SportsStore.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddsOrders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddsOrders));
        
        string IMigrationMetadata.Id
        {
            get { return "201712232012277_AddsOrders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
