// <auto-generated />
namespace SportsStore.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adds_product_soft_delete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adds_product_soft_delete));
        
        string IMigrationMetadata.Id
        {
            get { return "201805112210452_adds_product_soft_delete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
